# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activerecord` gem.
# Please instead update this file by running `bin/tapioca gem activerecord`.

module ActiveRecord; end
module ActiveRecord::EjectionSeat; end

# source://activerecord-ejection_seat/0.1.0/lib/activerecord-ejection_seat/version.rb#5
ActiveRecord::EjectionSeat::VERSION = T.let(T.unsafe(nil), String)
