# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-lsp` gem.
# Please instead update this file by running `bin/tapioca gem ruby-lsp`.

module RubyLsp; end

# source://ruby-lsp//lib/ruby-lsp.rb#5
RubyLsp::VERSION = T.let(T.unsafe(nil), String)

# source://tapioca/0.10.4/lib/tapioca/helpers/source_uri.rb#10
URI::Source::COMPONENT = T.let(T.unsafe(nil), Array)
