# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-struct-comparable` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-struct-comparable`.

module SorbetStructComparable; end

# source://sorbet-struct-comparable//lib/sorbet-struct-comparable/version.rb#5
SorbetStructComparable::VERSION = T.let(T.unsafe(nil), String)

# source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#10
T::Struct::ActsAsComparable::EQUAL = T.let(T.unsafe(nil), Integer)

# source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#11
T::Struct::ActsAsComparable::NOT_COMPARABLE = T.let(T.unsafe(nil), T.untyped)
