# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sorbet-struct-comparable` gem.
# Please instead update this file by running `bin/tapioca gem sorbet-struct-comparable`.

# source://sorbet-struct-comparable//lib/sorbet-struct-comparable/version.rb#4
module SorbetStructComparable; end

# source://sorbet-struct-comparable//lib/sorbet-struct-comparable/version.rb#5
SorbetStructComparable::VERSION = T.let(T.unsafe(nil), String)

# source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#6
module T::Struct::ActsAsComparable
  include ::Comparable

  # source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#14
  sig { params(other: ::Object).returns(T.nilable(::Integer)) }
  def <=>(other); end

  # source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#26
  sig { params(other: ::Object).returns(T::Boolean) }
  def eql?(other); end

  # source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#31
  sig { returns(::Integer) }
  def hash; end
end

# source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#10
T::Struct::ActsAsComparable::EQUAL = T.let(T.unsafe(nil), Integer)

# source://sorbet-struct-comparable//lib/t/struct/acts_as_comparable.rb#11
T::Struct::ActsAsComparable::NOT_COMPARABLE = T.let(T.unsafe(nil), T.untyped)
