require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Style/AccessorGrouping:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3
