name: Code Quality

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  tapioca:
    runs-on: ubuntu-latest
    name: Verify Tapioca RBIs were rebuilt
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true
    - run: bin/tapioca gem --verify
  sorbet:
    runs-on: ubuntu-latest
    needs: tapioca
    name: Sorbet typecheck on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rake sorbet
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bin/rubocop -c .rubocop.yml
  tests:
    runs-on: ubuntu-latest
    name: Tests on Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: rake test
